create table if not exists public.minesweeper_scores (
  id bigint generated by default as identity primary key,
  puzzle_key text not null,
  puzzle_name text not null,
  username text not null check (char_length(username) between 1 and 16),
  elapsed_ms bigint not null check (elapsed_ms > 0),
  played_at timestamptz not null default now()
);

create index if not exists minesweeper_scores_puzzle_key_idx
  on public.minesweeper_scores (puzzle_key);

create index if not exists minesweeper_scores_rank_idx
  on public.minesweeper_scores (puzzle_key, elapsed_ms, played_at);

alter table public.minesweeper_scores enable row level security;

drop policy if exists "public read scores" on public.minesweeper_scores;
create policy "public read scores"
  on public.minesweeper_scores
  for select
  to anon
  using (true);

drop policy if exists "anon insert scores" on public.minesweeper_scores;
create policy "anon insert scores"
  on public.minesweeper_scores
  for insert
  to anon
  with check (true);
